/**
 * PRP-226 PR2 — Kitchen Recommendation Engine types.
 *
 * Domain shapes consumed by:
 *   - CookabilityScorer / ExpiryScorer / PreferenceScorer  (pure functions)
 *   - RecommendationEngine                                 (orchestrator)
 *   - SuggestRecipesForContextHandler                      (assistant wrapper)
 *   - Future /api/recommendations/* routes (PR5, deferred)
 *
 * The output shape `RecommendedRecipeView` extends `CookableRecipeView`
 * so the existing assistant + frontend code (PRP-224 Sprint 2) keeps
 * working unchanged. Score parts and reasons are additive.
 */

import type { CookableRecipeView, RecipeSummaryView } from '../assistant/handlers/read.js';

// ---- Public goal enum ------------------------------------------------

/**
 * High-level intent the LLM (or future UI) declares. Used by the
 * engine to bias scoring (anti_waste boosts expiry, quick caps prep
 * time, etc.). Matches `SuggestRecipesForContextArgs.goal` enum.
 */
export type RecommendationGoal =
  | 'tonight'
  | 'quick'
  | 'anti_waste'
  | 'light'
  | 'high_protein'
  | 'comfort'
  | 'batch_cooking';

export type RecommendationMealType = 'breakfast' | 'lunch' | 'dinner' | 'snack';

// ---- Input context ---------------------------------------------------

/**
 * What the caller (assistant / route) hands to the engine. Every field
 * is optional ; the engine degrades gracefully when nothing is
 * provided (open question = sort by composite score with neutral hints).
 */
export interface RecommendationContext {
  /** Free-text the user typed/said. Stored verbatim in the audit event. */
  requestText?: string;
  /** ilike narrowing on `recipes.name`. */
  query?: string;
  mealType?: RecommendationMealType;
  goal?: RecommendationGoal;
  /** Max minutes (`prep_time + cook_time`). */
  timeLimitMinutes?: number;
  servings?: number;
  /** Cap for almost_cookable bucket (default 3). */
  almostThreshold?: number;
  /** Per-bucket limit (default 6). */
  limitPerBucket?: number;
  /** Window (in days) considered "near expiry" for the bonus. Default 7. */
  nearExpiryDays?: number;
  /** If false, suppress the fallback bucket. Default true. */
  includeRecentFallback?: boolean;
}

// ---- Score parts -----------------------------------------------------

/**
 * Each part lives in `[0, 1]` except `preferenceMatch` which can be
 * negative (a negative preference repels the recipe).
 * `missingPenalty` lives in `[0, 1]` — the formula subtracts it.
 */
export interface RecommendationScoreParts {
  cookability: number;
  expiryUrgency: number;
  preferenceMatch: number;
  timeFit: number;
  novelty: number;
  nutritionFit: number;
  effortFit: number;
  missingPenalty: number;
}

export interface RecommendationScore {
  /** Final clamped 0..100. */
  total: number;
  parts: RecommendationScoreParts;
}

// ---- Output ----------------------------------------------------------

export interface ExpiringIngredientHint {
  product_id: string;
  product_name: string;
  days_to_expiry: number;
}

export type SuggestedRecipeAction =
  | 'open_recipe'
  | 'add_missing_to_shopping'
  | 'plan_recipe'
  | 'mark_cooked';

/**
 * Extends `CookableRecipeView` (the legacy shape used by
 * AssistantRecipeProposals) with PRP-226 score + reasons + actions.
 * Backward compatible : existing consumers can ignore the new fields.
 */
export interface RecommendedRecipeView extends CookableRecipeView {
  /** Optional richer description (from `recipes.description`). */
  description?: string | null;
  servings?: number | null;
  cuisine_category?: string | null;
  meal_type?: string | null;
  tags?: string[] | null;
  /** Linked essentials the user does NOT have enough of. */
  unknown_ingredients?: string[];

  score_total: number;
  score_parts: RecommendationScoreParts;
  /** 2-4 short deterministic strings the LLM may reformulate. */
  reasons: string[];
  expiring_ingredients_used?: ExpiringIngredientHint[];
  suggested_actions: SuggestedRecipeAction[];
}

// ---- Engine result --------------------------------------------------

/**
 * 3-bucket result mirroring the legacy `SuggestRecipesResult` shape.
 * The handler wrapper adapts this to the existing tool output.
 */
export interface RecommendationResult {
  cookable_now: RecommendedRecipeView[];
  almost_cookable: RecommendedRecipeView[];
  recent_suggestions: RecipeSummaryView[];
  total_user_recipes: number;
  /** Generated by PR3 when the EventWriter is wired. */
  event_id?: string;
}

// ---- Engine inputs (loaded by orchestrator) -------------------------

/**
 * Raw recipe row + ingredients, as returned by Supabase. Mirrors what
 * `SuggestRecipesForContextHandler` queries today.
 */
export interface RecipeWithIngredients {
  id: string;
  name: string;
  description: string | null;
  prep_time: number | null;
  cook_time: number | null;
  servings: number | null;
  image_url: string | null;
  cuisine_category: string | null;
  meal_type: string | null;
  tags: string[] | null;
  created_at: string;
  recipe_ingredients:
    | Array<{
        id: string;
        ingredient_name: string;
        quantity: number;
        unit?: string | null;
        inventory_product_id: string | null;
        is_essential: boolean | null;
      }>
    | null;
}

/**
 * Inventory snapshot, indexed by `product_id` for O(1) lookup.
 * Built once per engine call from `inventory.select('product_id, quantity, expiry_date')`.
 */
export interface InventorySnapshotRow {
  product_id: string;
  quantity: number;
  expiry_date?: string | null;
  product_name?: string | null;
}

export interface InventorySnapshot {
  byProduct: Map<string, { quantity: number; expiryDate: string | null; productName: string | null }>;
}

// ---- Reason builder API ---------------------------------------------

/**
 * Reusable reason string. Engine assembles 2-4 of these per recipe.
 * Strings are deterministic ; the LLM is allowed to reformulate but
 * not invent new claims.
 */
export type RecommendationReason = string;
