// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwoxacnflphclslpqfzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3b3hhY25mbHBoY2xzbHBxZnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTk1ODYsImV4cCI6MjA2OTc3NTU4Nn0.Wy9XY3iniKxJmpXF3oHzjOADRm3NO6TDHVrIHhoT630";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});