// This file is automatically generated. Do not edit it directly.
// (Note: types.augmented.ts is hand-maintained — see comment header
// of that file. It re-exports `Database` augmented with the meal-
// planning tables that the upstream regen has fallen behind on.)
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.augmented';
import { config } from '@/config/client';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  config.supabase.url,
  config.supabase.anonKey,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);